genesis_id = ""
system = "Bancor"
dependencies = ["Ethereum"]
icon = "bancor"

[token]
name = "bancor"
symbol = "BANCOR"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Smart-contract-based Token Conversion Protocol"

[crowdsales]
start_date = "2017-06-12T10:00:00"
end_date = "2017-07-12T00:10:00"
end_date_plan = "2017-07-12T10:00:00"
genesis_address = [""]
funding_terms = "https://bancor.network/"
funding_url = "https://bancor.network/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "bancor.network"
url = "https://bancor.network/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Bancor Whitepaper"
url = "https://bancor.network/static/Bancor_Protocol_Whitepaper_en.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Bancor GitHub"
url = "https://github.com/bancorprotocol/contracts"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Bancor Blog"
url = "https://blog.bancor.network/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1789222.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/bancornetwork"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Bancor Slack"
url = "https://bancor-slack-invite.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Bancor/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCA125wWsdbsG1XPenWcBkyg"
icon = "youtube.png"
tags = ["News"]
